name: Python-course-BCGS-2020

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - numpy
  - matplotlib
  - scipy
  - sympy
  - colorama
  - pip:
    - jupyterlab_latex
    - jupyter_c_kernel
    